workspace(name = "gazelle_nix_example_vanilla")

local_repository(
    name = "io_tweag_gazelle_nix",
    path = "../..",
)

load("@io_tweag_gazelle_nix//gazelle_nix:repositories.bzl", "io_tweag_gazelle_nix_repositories")
io_tweag_gazelle_nix_repositories()

load("@io_tweag_gazelle_nix//gazelle_nix:deps.bzl", "io_tweag_gazelle_nix_deps")
io_tweag_gazelle_nix_deps()

load("@io_tweag_gazelle_nix//gazelle_nix:defs.bzl", "io_tweag_gazelle_nix_defs")
io_tweag_gazelle_nix_defs()
