package gazelle

import (
	"sort"

	"github.com/bazelbuild/bazel-gazelle/rule"
)

// FIXME: nixPackage should not carry information
// meant for build context target(s) i.e. nix_export
type nixPackage struct {
	name, nixFile, buildFile string
	nixFileDeps, nixOpts     []string
	repositories             map[string]string
}

func (pkg *nixPackage) ToRule() *rule.Rule {
	r := rule.NewRule(packageRule, pkg.name)
	r.SetAttr("nix_file", pkg.nixFile)
	r.SetAttr("nix_file_deps", pkg.nixFileDeps)
	r.SetAttr("nixopts", pkg.nixOpts)
	r.SetAttr("repositories", pkg.repositories)
	r.AddComment("# autogenerated")

	if len(pkg.buildFile) > 0 {
		r.SetAttr("build_file", pkg.buildFile)
	}

	return r
}

type nixExport struct {
	name  string
	files []string
}

func (pkg *nixExport) ToRule() *rule.Rule {
	sort.Strings(pkg.files)
	r := rule.NewRule(exportRule, pkg.name)
	r.SetAttr("files", pkg.files)
	r.AddComment("# autogenerated")

	return r
}
