workspace(name = "gazelle_nix_example_readtree")

local_repository(
    name = "io_tweag_gazelle_nix",
    path = "../..",
)

load("@io_tweag_gazelle_nix//:repositories.bzl", "io_tweag_gazelle_nix_repositories")

io_tweag_gazelle_nix_repositories()

load("@io_tweag_gazelle_nix//:deps.bzl", "io_tweag_gazelle_nix_deps")

io_tweag_gazelle_nix_deps()

load("@io_tweag_gazelle_nix//:setup.bzl", "io_tweag_gazelle_nix_setup")

io_tweag_gazelle_nix_setup()

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_local_repository",
)

nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//nix/nixpkgs:default.nix",
    nix_file_deps = [
        "//nix/nixpkgs:nixpkgs.json",
    ],
)
